name: Electron

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18
          pnpm-version: 8.14.0
      - name: Get xvfb
        run: sudo apt-get install xvfb  
      - name: Electron Test
        run: xvfb-run --auto-servernum pnpm test:electron   