name: Linting

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: JS and HBS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.14.0
      - name: Lint JS
        run: pnpm lint:js
      - name: Lint HBS
        run: pnpm lint:hbs
