name: Package and Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
          with:
            node-version: '10.x'
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies (yarn)
        run: yarn install
      - name: Package App
        run: yarn make
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: electron-out/**/*.zip
