name: Package and Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Yarn install
        run: yarn run install-deps
      - name: Make
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: electron-out/**/*.zip
